install:
  - pip install --user Sphinx
  - pip install --user sphinx_rtd_theme

script:
  - make html

deploy:
  provider: pages
  repo: uob-hpc/zoo
  target-branch: gh-pages
  local-dir: _build/html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master

